#Base Imagen Ubuntu:14.04
FROM mysql:5.7

#Definimos deirectorio de trabajo
WORKDIR /var/lib/mysql

#Creamos enlace entre carpeta anfitrio y carpeta contenedor 
VOLUME mysql

EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD=karloz
